### ISSUE TITLE
Do we need a fixed discriminator when training the generator in dcgan_mnist.py?

### ISSUE THREAD

**Issue by luyfuyu** [roatienza/Deep-Learning-Experiments#1]
thanks for your article (https://medium.com/towards-data-science/gan-by-example-using-keras-on-tensorflow-backend-1a6d515a60d0), i like it. But i have a question want to ask you:

Do we need a fixed discriminator when training the generator in dcgan_mnist.py?

because i think it need fixed.

thanks

**Comment by roatienza** [comment]
In some GAN implementations, the discriminator is pre-trained before it is used. However, I think it is a bad idea since most of the time, the discriminator converges faster than the generator. So, having a pre-trained discriminator can no longer contribute much in the training of the generator. In fact, you should allow the generator to catch up to the discriminator during training.

**Comment by luyfuyu** [comment]
ok, isee, thanks for you answer very much!
